### PR TITLE
Add svg and raster logos

### PR DESCRIPTION
**Pull request by pulsar17**
Earlier discussion in #1 

The normal variant (what I call plain in README)  is an optimized SVG (can be created using _File > Save a Copy > Optimized SVG_ in Inkscape, the size is even smaller than a Plain SVG I mentioned in #1).

- [x] The source file license is [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)
- [x] Added a round variant (In fact, the base SVG is the round variant, other ones can be created from it fairly easily)
- [x] Added a PNG along with WebP

### CODE REVIEW

**Comment by gswebspace** [comment]
Looks good. @pulsar17 Can a LICENSE file be added to the repo to have the license be explicitly visible to any viewer of the repo.

or if it is easier update the README.md and explictly mention that the logo is CC-SA and attributions ?

**Review by ditsuke — APPROVED** [review]
LGTM

**Comment by pulsar17** [comment]
@gswebspace I've added the license as suggested by the [CC BY-SA 4.0 page](https://creativecommons.org/choose/results-one?license_code=by-sa&amp;jurisdiction=&amp;version=4.0&amp;lang=en)

This should suffice, I don't think a separate LICENSE file is required.

About mentioning who to attribute to in the README, there are two choices:

1. Since I'll be the licensor according to [Attributing an image [CC Wiki]](https://wiki.creativecommons.org/wiki/best_practices_for_attribution#Attributing_an_image), I can choose the attribution. So, 
- @gswebspace do you want to be attributed? And if so what name should I use? (Since these logos are a derivative of your work which is a derivative of my work.)
- @yash-raj10 do you want to be attributed? And if so what name should I use? (Since my work can be considered a derivative of your work)
2. Skip the attribution part, just not do it. (_Good faith option_ - also note that the attribution **is** embedded in the svg, so it's not like it's not present _anywhere_) 

Apologies if I am being too pedantic about it, I just want to ensure that this concern is noted somewhere.

**Comment by gswebspace** [comment]
@pulsar17 I would like you and yash to get recognition of the work done to make the logo possible. 
So I would prefer explicit attribution in the README.md file for all contributors.

**Comment by yash-raj10** [comment]
That will be good @gswebspace .
But yaa if you want you can add the attribute as "Yash-raj" @pulsar17 (onto you)

Thank you!

**Comment by gswebspace** [comment]
@pulsar17 you can simply mention my name `Guinnes Singh` for the Attribution. Please update the README and I can go ahead and merge the PR.

**Comment by pulsar17** [comment]
@gswebspace 
- [x] License added
- [x] Attribution information added

**Pull request merged**
