### PR TITLE
Added Rust Delhi Logo (svg and jpg)

### PR DESCRIPTION
**Pull request by yash-raj10**

### CODE REVIEW

**Comment by gswebspace** [comment]
Hi @yash-raj10 ! Thanks for sharing the svg. I tried to open it with Inkscape and saw some extra lines as seen below:

image

These also show up if I export a jpg.

Can you let me know which image editing software you use to get a smooth view/jpg export of this ?

Also please check if the svg renders properly for you using [Inkscape](https://inkscape.org/) ?
Please share an updated SVG if you also see the same issue.

**Comment by yash-raj10** [comment]
Hey, sorry for the late reply my exams just ended today, and yaa I got the
lines too in the svg one but jpg looks fine to me (Didn't find any lines
there)... I converted the jpg to svg using Adobe Express
<https://www.adobe.com/express/feature/image/convert/jpg-to-svg>

Do you want me to add another PR ?

**Comment by gswebspace** [comment]
@yash-raj10 You can update the files in this branch/PR since it has not merged yet. It should get updated automatically.

**Comment by gswebspace** [comment]
Just reviewed the latest files and I seem to be getting the same lines using the SVG in Inkscape. 
These will cause issues while rendering on website or while printing.

We can try recreating the logo from the vector files of the parts used if available. 
I can try to recreate the final smooth vector image from them. 

Otherwise we may have to recreate the whole thing in Inkscape from scratch.

Let me know if there are any other vector files available of the parts in the logo ?

Thanks!

**Comment by pulsar17** [comment]
@gswebspace I've made a clean room implementation of @yash-raj10 's logo:

rustdelhi-logo-final


All shapes are custom, so we don't need to worry about any licensing restrictions.
Feel free to modify them (that's kind of the point I'm putting this here.)

I don't think we decided upon a license for the assets. Until that is decided, this svg is under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)

If a different license is required, I'll be happy to change it.

**Comment by yash-raj10** [comment]
Thanks for this one @pulsar17 , appreciated :)

**Comment by gswebspace** [comment]
Thanks @pulsar17 ! Appreciate the effort put in to create the SVG. I have updated the logo to fix a minor overlap issue. Attached updated SVG.
rustdelhi_logo

Regarding the license of the logo, we did discuss the policy around it as mentioned in the policies repo: https://github.com/rustdelhi/policies/blob/main/Licensing.md

The license chosen was restrictive only for the logo, primarily so as to prevent any misuse of the logo, targeting the community. 

Having said that, I am open to CC Attribution license be the logo's source file license, while being optimistic that misuse would be very unlikely and can't really be prevented practically.

Requesting final review by @ditsuke. 

@ditsuke Let me know if we can go ahead and accept the latest attached SVG in this message as the logo under CC Attribution license, attributing Yash and Ishaan ?

**Comment by pulsar17** [comment]
Sure, I am ok with dropping the *Share-Alike* version of the CC license to conform to https://github.com/rustdelhi/policies/blob/main/Licensing.md

I have a few suggestions:
-  Upload two versions, an Inkscape SVG and a *plain* SVG for web (_File > Export > Plain SVG_). This way, the editability part will be present in the Inkscape svg. The Inkscape version also contains some extra metadata. (_Not strictly required but good to have._) The plain svg will be smaller
- Change the license of the source svg in Inkscape to the one in the policies doc. It can be changed in Inkscape by going to File > Document Properties > Metadata. Inkscape then embeds the license information in the svg file itself. 

  image
- Add a round variant (I think @yash-raj10 intended the logo to be circular):
   ### Logo Round
   rustdelhi-logo-guinnes-round

  I've changed the license (like I suggested above) and added @gswebspace as a contributor to the svg. (You can view this metadata either by opening the SVG file using a text editor, or by doing _Inspect Element_ on the image in a browser.)

- Instead of using a _jpg_, we should use _webp_ as the raster format (_File > Export > WebP_).
- I think there should be a separate clean PR for the logos. I'll be happy to create one if required.

**Comment by gswebspace** [comment]
@pulsar17 Apologies, my sleepy head last night misread the CC-SA to CC-A. I am also OK with using ShareAlike version of CC license so no change needed.

Please open a new PR with the Round Variant and reference this PR in it as well. Include all changes you have suggested and also export a png version along with webp.

**Pull request closed without merging**
